#ifndef _ARGON_RESOURCES_H_
#define _ARGON_RESOURCES_H_

#define ARGON_RES_ADDR 0xEE000000

#define MONTSERRAT_12_GLYPH_BMP 0x0
#define MONTSERRAT_12_GLYPH_DSC 0x9FE
#define MONTSERRAT_12_KERN_PAIR_GLYPH 0xA5E
#define MONTSERRAT_12_KERN_PAIR_VALUE 0x1056

void argon_resources_init();

#endif // _ARGON_RESOURCES_H_